---
version: '3'

services:
  whistleblower:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SERVER_PORT: ":8080"
      LOG_LEVEL: "debug"
      LOG_FORMAT: "text"
      POSTGRES_ADDRESS: "postgres:5432"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DATABASE: "whistleblower"
      POSTGRES_LOG_ENABLED: "false"
      POSTGRES_MAX_IDLE_CONN: 2
      POSTGRES_MAX_OPEN_CONN: 10
    ports:
      - 8080:8080
    expose:
      - 8080
    links:
      - postgres:postgres
    depends_on:
      - wait-for-it

  wait-for-it:
    image: willwill/wait-for-it
    command: ["postgres:5432 -t 60 -- echo postgres is up"]
    links:
      - postgres:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: "whistleblower"
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"